# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01e28d61ef3dcf97a7b4d35937beebc360b8954e279b794221b5633d0db72c3b7c784826341e86306ea8b74918e0385271a7e357d0977fdd7086d33ba2a8ea9f

test:
  secret_key_base: 15d8ac63a320ade07e8c0b753668e1ddbf09a7d7ff6b51c4b0ec8c117f47ccabcac87891d55c544063d32d12d24d7337c0abec5128c0726aea0838542abdedef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
